'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CfgTagRecord
    Public Property TagId As Integer
    Public Property GroupId As Integer
    Public Property TagName As String
    Public Property Description As String
    Public Property HwTagName As String
    Public Property HwTagType As Integer
    Public Property HwDataType As Integer
    Public Property Elements As Integer
    Public Property StringLenth As Integer
    Public Property OptimizeReads As Boolean
    Public Property SimType As Integer
    Public Property TagRole As Integer
    Public Property RateChangeThreshold As Single
    Public Property Folder As String

End Class
