'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeviceRecord
    Public Property WorkCellId As Integer
    Public Property DeviceId As Integer
    Public Property Description As String
    Public Property DeviceName As String
    Public Property DeviceType As Integer
    Public Property Model As Integer
    Public Property Driver As Integer
    Public Property RoutePath As String
    Public Property Simulate As Boolean
    Public Property TimeOutConnect As Integer
    Public Property TimeOutTransaction As Integer
    Public Property AddressingType As Integer
    Public Property MaxDataBytesRead As Integer
    Public Property MaxDataBytesWrite As Integer
    Public Property WordSwapFloat As Boolean
    Public Property WordSwapLong As Boolean
    Public Property WriteCoilFunction As Integer
    Public Property WriteRegisterFunction As Integer
    Public Property DeviceError As String
    Public Property ChannelError As String
    Public Property ComPort As String
    Public Property PortSettings As String
    Public Property PortDtrControl As Integer
    Public Property PortRtsControl As Integer
    Public Property SerialProtoCol As Integer
    Public Property SerialMsgDelay As Integer
    Public Property LinkType As Integer

End Class
