'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Eqp_PartResults
    Public Property Code As Integer
    Public Property LineId As Integer
    Public Property Description As String

    Public Overridable Property eqp_Lines As eqp_Lines

End Class
