'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ErgonomicCategoryRecord
    Public Property ErgId As Integer
    Public Property Name As String
    Public Property erg_Durration_Hrs As Decimal
    Public Property erg_Span_Hrs As Decimal
    Public Property erg_Rest_Hrs As Decimal

    Public Overridable Property eqp_Stations As ICollection(Of StationRecord) = New HashSet(Of StationRecord)

End Class
