'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Magna_LowellEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Magna_LowellEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property LineRecords() As DbSet(Of LineRecord)
    Public Overridable Property ErgonomicCategoryRecords() As DbSet(Of ErgonomicCategoryRecord)
    Public Overridable Property CfgTagRecords() As DbSet(Of CfgTagRecord)
    Public Overridable Property PartResultRecords() As DbSet(Of PartResultRecord)
    Public Overridable Property StatusEnumRecords() As DbSet(Of StatusEnumRecord)
    Public Overridable Property StationRecords() As DbSet(Of StationRecord)
    Public Overridable Property GroupRecords() As DbSet(Of GroupRecord)
    Public Overridable Property DeviceRecords() As DbSet(Of DeviceRecord)

End Class
