'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Magna_LowellEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Magna_LowellEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CfgTagRecords() As DbSet(Of CfgTagRecord)
    Public Overridable Property GroupRecords() As DbSet(Of GroupRecord)
    Public Overridable Property DeviceRecords() As DbSet(Of DeviceRecord)
    Public Overridable Property Eqp_ErgonomicCategories() As DbSet(Of Eqp_ErgonomicCategories)
    Public Overridable Property eqp_Lines() As DbSet(Of eqp_Lines)
    Public Overridable Property Eqp_PartResults() As DbSet(Of Eqp_PartResults)
    Public Overridable Property Eqp_StateEnum() As DbSet(Of Eqp_StateEnum)
    Public Overridable Property eqp_Stations() As DbSet(Of eqp_Stations)

End Class
