'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StationRecord
    Public Property StationId As Integer
    Public Property LineId As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property ErgonomicId As Integer
    Public Property MinTrainingHours As Integer
    Public Property DaysofConsideration As Integer
    Public Property StatusTagId As Nullable(Of Integer)
    Public Property ShopLogixFolderName As String
    Public Property StationName As String
    Public Property StationDefinition As String
    Public Property StateTagId As Nullable(Of Integer)

    Public Overridable Property Eqp_ErgonomicCategories As ErgonomicCategoryRecord
    Public Overridable Property eqp_Lines As LineRecord
    Public Overridable Property Eqp_StateEnum As ICollection(Of StatusEnumRecord) = New HashSet(Of StatusEnumRecord)

End Class
